### PR TITLE
Move build config to pyproject.toml

### LINKED ISSUE #63: Move to pyproject.toml
This project uses the setup.cfg, which will be deprecated at some point.

I want to move the build system to pyproject.toml, which is the current python standard and the ['the one true way to do declarative builds'](https://peps.python.org/pep-0518/), project metadata, and other tool config.

### PR DESCRIPTION
**Pull request by stefsmeets**
This PR moves the build config to `pyproject.toml`. I also cleaned up a few files.

Closes #63

## Todo

- [x] merge main after #62

### CODE REVIEW

**Comment by stefsmeets** [comment]
Hi @kodymoodley @ThijsVroegh Any chance we could get this reviewed and merged? 😅

**Comment by kodymoodley** [comment]
Hi @stefsmeets, does this change in the build config affect the deployment of new versions of the add-on? I have setup some Github actions to automatically deploy to PyPI whenever a new release is made. Also I am not sure but I think the [readthedocs](https://orange-story-navigator.readthedocs.io/en/latest/) depends on some of the current build config.

**Comment by stefsmeets** [comment]
Hi @kodymoodley you still do `pip install -e .` or `pip install storynavigator` to install the package, if that is what you mean.

The rtd build is separate from the build system, although it will use this code to install the package. If there is an unforeseen breakage I will fix it.

Once this is merged I plan to have a look at the automated deploy to pypi etc in #65

**Comment by kodymoodley** [comment]
> Hi @kodymoodley you still do `pip install -e .` or `pip install storynavigator` to install the package, if that is what you mean.
> 
> The rtd build is separate from the build system, although it will use this code to install the package. I think it also just does `pip install .`. If there is an unforeseen breakage I will fix it.
> 
> Once this is merged I plan to have a look at the automated deploy to pypi etc in #65

Okay @stefsmeets glad to know you can fix if there is a breakage. You can go ahead and merge then.

**Pull request merged**
